# Only some example scorers are listed here. Please refer to all_scorers.yaml for all scorers

model_cache_path: '../ckpt' # cache path for models

data:
  text:
    use_hf: False # Whether to use huggingface_dataset, if used, ignore the local data path below
    dataset_name: 'yahma/alpaca-cleaned'
    dataset_split: 'train'  
    name: 'default' 
    # /mnt/hwfile/opendatalab/zhangchi/slimpajama-10/clustering-0.jsonl
    # /mnt/petrelfs/baitianyi/eval/Open-DataFlow-Eval/demos/text_eval/alpaca_5_samples.json
    # /mnt/petrelfs/baitianyi/eval/Open-DataFlow-Eval/demos/text_eval/fineweb_5_samples.json
    data_path: '/mnt/petrelfs/baitianyi/eval/Open-DataFlow-Eval/demos/text_eval/fineweb_5_samples.json'  # Local data path, supports json, jsonl, parquet formats
    formatter: "TextFormatter" # Data loader type

    keys: ['instruction','input','output'] # Key name to be evaluated, for sft data, it can be specified as ['instruction','input','output']. For pt data, 'context'
    
scorers: # You can select multiple text scorers from all_scorers.yaml and put their configuration information here
  LexicalDiversityScorer:  # 文本不能太长
    metrics_to_keep:
      mtld: True
      hdd: True
  NgramScorer:
    ngrams: 5
  LangkitScorer:
      metrics_to_keep:
        flesch_reading_ease: True
        automated_readability_index: True
        aggregate_reading_level: True
        syllable_count: True
        lexicon_count: True
        sentence_count: True
        character_count: True
        letter_count: True
        polysyllable_count: True
        monosyllable_count: True
        difficult_words: True
  TextbookScorer: # cpu(fasttext)
      model_repo: 'kenhktsui/llm-data-textbook-quality-fasttext-classifer-v2'
      model_file: 'model.bin'
      low_score: 0
      mid_score: 1
      high_score: 2
      batch_size: 8
  PerplexityScorer: # cpu(Kenlm)
      model_path: 'dataflow/Eval/Text/models/Kenlm/wikipedia' # please refer to https://huggingface.co/edugp/kenlm/tree/main and download the corresponding model, such as wikipedia
      language: 'en'
  QuratingScorer:
      model: 'princeton-nlp/QuRater-1.3B'
      tokens_field: 'input_ids'
      tokens: 512
      map_batch_size: 512
      num_workers: 5
      device_batch_size: 16
      device: 'cuda'
      labels:
        - writing_style
        - required_expertise
        - facts_and_trivia
        - educational_value
  PresidioScorer:
      language: 'en'
      device: 'cuda'
  Task2VecScorer:
      sample_nums: 2 # sampling times
      sample_size: 8 # batch size for one sample
      device: 'cuda'
      method: 'montecarlo' # from [montecarlo, variational]
  VendiScorer:
      bert_model_path: 'bert-base-uncased'
      simcse_model_path: 'princeton-nlp/unsup-simcse-bert-base-uncased'
      device: 'cuda'
      metrics_to_keep: 
        ngram: True
        bert: True
        simcse: True
  UnievalScorer:
      device: 'cuda'
      metrics_to_keep:
        fluency: True
        naturalness: True
        understandability: True
  SuperfilteringScorer:
    device: 'cuda'
    model_name: 'gpt2'
    prompt: 'none'
    max_length: 1024
  RMScorer:
    model_name: 'OpenAssistant/reward-model-deberta-v3-large-v2'  
    device: 'cuda' 
    batch_size: 64 
  InstagScorer:
      model_path: 'OFA-Sys/InsTagger'
      temperature: 0
      do_sample: False
      max_new_tokens: 2048 
      num_return_sequences: 1
      return_dict_in_generate: True
      device: 'cuda'
  FineWebEduScorer:
    model_name: 'HuggingFaceTB/fineweb-edu-classifier'
    device: 'cuda'
  DebertaV3Scorer:
    model_name: 'nvidia/quality-classifier-deberta'
    device: 'cuda'
    batch_size: 16
  DeitaQualityScorer:
    device: 'cuda'
    model_name: 'hkust-nlp/deita-quality-scorer'
    max_length: 512
  DeitaComplexityScorer:
    device: 'cuda' 
    model_name: 'hkust-nlp/deita-complexity-scorer' 
    max_length: 512
  PerspectiveScorer:
    api_key: 'Your Key'
    api_name: 'commentanalyzer'
    api_version: 'v1alpha1'
    discovery_service_url: 'https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1'
    static_discovery: False